language: android

android:
  components:
  - build-tools-29.0.2
  - android-29

before_install:
  - openssl aes-256-cbc -K $key -iv $iv -in key_store.jks.enc -out key_store.jks -d
  - openssl aes-256-cbc -K $key -iv $iv -in license_key.xml.enc -out app/src/main/res/values/license_key.xml -d

script:
  - ./gradlew build

# deploy:
#   provider: releases
#   api_key:
#     secure: YOUR_API_KEY_ENCRYPTED
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
